name: Daily YouTube ETL

on:
  schedule:
    - cron: '0 13 * * *'  # 9AM EST daily
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install google-api-python-client google-cloud-bigquery pandas matplotlib

      - name: Decode service account key
        run: echo "$GCP_CREDENTIALS_B64" | base64 --decode > key.json
        env:
          GCP_CREDENTIALS_B64: ${{ secrets.GCP_CREDENTIALS_B64 }}

      - name: Run ETL script
        run: python youtube_etl.py
